name: FAKE Build and Test

on:
    [push, pull_request]

jobs:
    build:

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-13]
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET 6
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '6.0.301'
            - name: Setup .NET 8
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.304'
            - name: Restore dotnet tools
              run: dotnet tool restore
            - name: remove current fake runner tool
              run: dotnet tool uninstall fake-cli
            - name: Build fake runner
              run: dotnet pack --version-suffix 1 src/app/fake-cli/fake-cli.fsproj
            - name: add fake runner as a tool
              run: dotnet tool install fake-cli --add-source "./src/app/fake-cli/bin/Debug" --add-source "./src/app/fake-cli/bin/Release" --version 1.0.0-1
            - name: Build
              run: dotnet fake -v build --parallel 3 -e FAKE_DETAILED_ERRORS=true
            - name: publish build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: fake-artifacts-${{ matrix.os }}
                  path: release/artifacts
